baseURL = "https://jordiortegon.github.io"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"


[languages]
  [languages.en]
    title = "English"
    weight = 1
    [languages.en.params]
      path  = "/en"
      home = "HOME"
  [languages.es]
    title = "Español"
    weight = 2
    [languages.es.params]
      path  = "/es"
      home = "INICIO"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[languages.en.menu.header]]
  name = "About"
  URL = "#about"
  weight = 2
  
  [[languages.es.menu.header]]
  name = "Sobre"
  URL = "#sobre"
  weight = 2

  [[languages.en.menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[languages.es.menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[languages.en.menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[languages.es.menu.header]]
  name = "Contacto"
  URL = "#contacto"
  weight = 4

  [[languages.en.menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[languages.es.menu.footer]]
  name = "Sobre"
  URL = "#sobre"
  weight = 2

  [[languages.en.menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[languages.es.menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[languages.en.menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[languages.es.menu.footer]]
  name = "Contacto"
  URL = "#contacto"
  weight = 4

[params]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Jordi"

  [params.footer]